import type { LeaderboardEntry, LeaderboardEntryDate } from '@top-x/shared/types/game';
export declare const DEFAULT_LEADERBOARD_PHOTO = "https://top-x.co/assets/profile.png";
export declare const formatLeaderboardDailyIndex: (date: Date) => string;
export declare const formatLeaderboardWeeklyIndex: (date: Date) => string;
export declare const formatLeaderboardMonthlyIndex: (date: Date) => string;
export declare const createLeaderboardDatePayload: (timestamp: number | null | undefined) => LeaderboardEntryDate | undefined;
export declare const parseDateLikeValue: (value: unknown) => number | undefined;
export declare const mapLeaderboardDoc: (docSnapshot: FirebaseFirestore.QueryDocumentSnapshot<FirebaseFirestore.DocumentData> | FirebaseFirestore.DocumentSnapshot<FirebaseFirestore.DocumentData>) => LeaderboardEntry;
export declare const toOptionalString: (value: unknown) => string | undefined;
export declare const getLeaderboardCollectionRef: (gameId: string, dailyChallengeId?: string) => FirebaseFirestore.CollectionReference<FirebaseFirestore.DocumentData>;
