import type { PageContentDefaults } from '../types/content';

export const PAGE_CONTENT_DEFAULTS: PageContentDefaults = {
  contact: {
    en: {
      content: {
        'hero.pill': 'Need a hand?',
        'hero.title': 'Contact the TOP-X team',
        'hero.subtitle': 'We’re here to help with partnerships, community questions, and support for your games.',
        'sections.talk.title': 'Talk to us',
        'sections.talk.body': 'For support, questions, or feedback, email the crew. We reply within two business days.',
        'sections.talk.linkLabel': 'support@top-x.co',
        'sections.talk.linkHref': 'mailto:support@top-x.co',
        'sections.follow.title': 'Follow the updates',
        'sections.follow.body': 'Join the conversation on X to hear about new games, creator spotlights, and live drops.',
        'sections.follow.linkLabel': '@Topxapp',
        'sections.follow.linkHref': 'https://x.com/Topxapp',
        'cta.label': 'Back to home',
        'cta.href': '/',
      },
      seo: {
        title: 'Contact TOP-X',
        description: 'Get in touch with the TOP-X team for support, partnerships, and community updates.',
        keywords: 'TOP-X contact, support, partnerships, community',
      },
    },
    il: {
      content: {
        'hero.pill': 'צריכים עזרה?',
        'hero.title': 'צרו קשר עם צוות TOP-X',
        'hero.subtitle': 'אנחנו כאן בשביל שיתופי פעולה, שאלות מהקהילה ותמיכה במשחקים שלכם.',
        'sections.talk.title': 'דברו איתנו',
        'sections.talk.body': 'לתמיכה, שאלות או פידבק – כתבו לצוות. אנחנו חוזרים אליכם תוך שני ימי עסקים.',
        'sections.talk.linkLabel': 'support@top-x.co',
        'sections.talk.linkHref': 'mailto:support@top-x.co',
        'sections.follow.title': 'עקבו אחרי העדכונים',
        'sections.follow.body': 'הצטרפו לשיחה ב-X כדי לשמוע על משחקים חדשים, ספוטים ליוצרים ודרופים בלייב.',
        'sections.follow.linkLabel': '@Topxapp',
        'sections.follow.linkHref': 'https://x.com/Topxapp',
        'cta.label': 'חזרה לבית',
        'cta.href': '/',
      },
      seo: {
        title: 'צור קשר עם TOP-X',
        description: 'דברו עם צוות TOP-X לשיתופי פעולה, תמיכה ועדכונים מהקהילה.',
        keywords: 'TOP-X, צור קשר, תמיכה, שיתופי פעולה',
      },
    },
  },
  build: {
    en: {
      content: {
        'hero.pill': 'Creator tools',
        'hero.title': 'Build your own game',
        'hero.subtitle': 'Launch a custom experience in minutes. Pick a template, tweak the prompts, and share it with your community.',
        'hero.cta.reminder': 'Sign in to unlock the builder.',
        'hero.cta.button': 'Login with X',
        'stats.templates.label': 'Game templates',
        'stats.games.label': 'Drafts & live games',
        'locked.title': 'Ready to create?',
        'locked.body': 'Only logged-in creators can publish new challenges. Connect your X account to get started.',
        'locked.button': 'Login',
        'templates.title': 'Choose a game template',
        'templates.subtitle': 'Start from a curated format designed for fast play.',
        'templates.empty': 'Templates are loading. Check back in a moment.',
        'games.title': 'My games',
        'games.subtitle': 'Manage drafts, publish live games, and curate daily challenges.',
        'games.empty': 'You haven’t created any games yet. Pick a template to start building.',
        'editor.back': '← Back to templates',
        'editor.heading.create': 'Create {template} game',
        'editor.heading.edit': 'Edit {template} game',
        'editor.subtitle': 'Configure prompts, scoring, and appearance before sharing it with players.',
      },
      seo: {
        title: 'Build games - TOP-X',
        description: 'Create custom games, manage drafts, and curate daily challenges for your community on TOP-X.',
        keywords: 'TOP-X builder, create games, community challenges',
      },
    },
    il: {
      content: {
        'hero.pill': 'כלי יוצרים',
        'hero.title': 'בנו משחק משלכם',
        'hero.subtitle': 'השיקו חוויה מותאמת אישית בדקות. בחרו תבנית, כוונו את הפרומפטים ושתפו את הקהילה שלכם.',
        'hero.cta.reminder': 'התחברו כדי לפתוח את הבונה.',
        'hero.cta.button': 'התחברות עם X',
        'stats.templates.label': 'תבניות משחק',
        'stats.games.label': 'טיוטות ומשחקים פעילים',
        'locked.title': 'מוכנים ליצור?',
        'locked.body': 'רק יוצרים מחוברים יכולים לפרסם אתגרים חדשים. התחברו עם חשבון ה-X שלכם כדי להתחיל.',
        'locked.button': 'התחברות',
        'templates.title': 'בחרו תבנית משחק',
        'templates.subtitle': 'התחילו מפורמט שנבנה למשחק מהיר.',
        'templates.empty': 'תבניות נטענות. שווה לבדוק שוב בקרוב.',
        'games.title': 'המשחקים שלי',
        'games.subtitle': 'נהלו טיוטות, פרסמו משחקים חיים ואצרו אתגרי יומיום.',
        'games.empty': 'עוד לא יצרתם משחקים. בחרו תבנית כדי להתחיל לבנות.',
        'editor.back': '← חזרה לתבניות',
        'editor.heading.create': 'יצירת משחק {template}',
        'editor.heading.edit': 'עריכת משחק {template}',
        'editor.subtitle': 'הגדירו פרומפטים, ניקוד ומראה לפני השיתוף עם השחקנים.',
      },
      seo: {
        title: 'בנו משחקים - TOP-X',
        description: 'צרו משחקים מותאמים, נהלו טיוטות ואצרו אתגרי קהילה ב-TOP-X.',
        keywords: 'TOP-X, בניית משחקים, אתגרים לקהילה',
      },
    },
  },
  terms: {
    en: {
      content: {
        'hero.pill': 'Legal',
        'hero.title': 'Terms of Use',
        'hero.subtitle': 'Effective Date: July 17, 2025',
        'sections.1.title': 'Welcome to TOP-X',
        'sections.1.body': 'By using our games and services, you agree to follow these terms. TOP-X is built for friendly competition and shared entertainment. Users must be 18+ (or have guardian approval) and comply with local laws when creating or sharing content.',
        'sections.2.title': 'Player responsibilities',
        'sections.2.body': 'Keep your account secure, respect community guidelines, and avoid harmful or offensive submissions. We reserve the right to moderate, remove content, or suspend accounts that violate the vibe.',
        'sections.3.title': 'Updates to the terms',
        'sections.3.body': 'We may update these terms as the platform evolves. Significant changes will be announced through the app or email. Continued use after updates indicates acceptance.',
        'cta.label': 'Back to home',
        'cta.href': '/',
      },
      seo: {
        title: 'TOP-X Terms of Use',
        description: 'Terms of Use for the TOP-X gaming platform, covering player responsibilities and policies.',
        keywords: 'TOP-X terms, policies, legal',
      },
    },
    il: {
      content: {
        'hero.pill': 'משפטי',
        'hero.title': 'תנאי שימוש',
        'hero.subtitle': 'תאריך תחולה: 17 ביולי 2025',
        'sections.1.title': 'ברוכים הבאים ל-TOP-X',
        'sections.1.body': 'בשימוש במשחקים ובשירותים שלנו אתם מסכימים לעמוד בתנאים אלו. TOP-X נבנתה לתחרות ידידותית ולחוויה משותפת. משתמשים חייבים להיות בני 18+ (או עם אישור אפוטרופוס) ולעמוד בחוקים המקומיים בעת יצירה או שיתוף תוכן.',
        'sections.2.title': 'אחריות השחקנים',
        'sections.2.body': 'שמרו על חשבון מאובטח, כבדו את כללי הקהילה והימנעו מהגשות פוגעניות או מזיקות. אנו שומרים לעצמנו את הזכות למתן, להסיר תוכן או להשעות חשבונות שמפרים את הווייב.',
        'sections.3.title': 'עדכונים לתנאים',
        'sections.3.body': 'ייתכנו עדכונים לתנאים בהתאם להתפתחות הפלטפורמה. נודיע על שינויים משמעותיים באפליקציה או במייל. המשך שימוש לאחר העדכון מהווה הסכמה.',
        'cta.label': 'חזרה לבית',
        'cta.href': '/',
      },
      seo: {
        title: 'תנאי שימוש - TOP-X',
        description: 'תנאי השימוש של פלטפורמת TOP-X: אחריות שחקנים ומדיניות הפלטפורמה.',
        keywords: 'TOP-X, תנאי שימוש, מדיניות',
      },
    },
  },
};
