import { postOnX } from './external/xApi';
import './utils/firebaseAdmin';
export declare const syncXUserData: any;
export declare const submitGameScore: any;
export declare const getTopLeaderboard: any;
export declare const setGameFavorite: any;
export declare const getAroundLeaderboard: any;
export declare const getFriendsLeaderboard: any;
export declare const getPercentileRank: any;
export declare const getVipLeaderboard: any;
export { postOnX };
